"""
export.py — reads the SQLite DB + config.json and writes data.js next to
dashboard.html.

data.js declares two globals:
    window.EXPENSE_DATA   = [ {id, date, category, amount, note, type}, ... ]
    window.EXPENSE_CONFIG = { currency, monthlyBudget, budgets, categories }

dashboard.html loads this via <script src="data.js"></script> (NOT fetch),
so it works straight from file:// with zero server. The Telegram bot token
is deliberately NEVER included here — only currency/budget/category info,
which is safe to sit in a browser-readable file.
"""

import json
from pathlib import Path

import db

BASE_DIR = Path(__file__).parent
CONFIG_PATH = BASE_DIR / "config.json"
DATA_JS_PATH = BASE_DIR / "data.js"

# Keep this in sync with parser.CATEGORY_KEYWORDS keys (+ "income").
ALL_CATEGORIES = [
    "rent", "food", "groceries", "travel", "bills", "emis", "insurance",
    "investments", "emergency", "clothes", "luxuries", "health", "education", "other",
]


def load_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        cfg = json.load(f)
    return cfg


def export():
    cfg = load_config()
    rows = db.all_rows()

    public_config = {
        "currency": cfg.get("currency", "₹"),
        "monthlyBudget": cfg.get("monthlyBudget", 0),
        "budgets": cfg.get("budgets", {}),
        "categories": ALL_CATEGORIES,
    }

    # Strip chat_id from the browser-facing data — it's irrelevant to the
    # dashboard and there's no reason to expose it.
    public_rows = [
        {
            "id": r["id"],
            "date": r["date"],
            "category": r["category"],
            "amount": r["amount"],
            "note": r["note"],
            "type": r["type"],
        }
        for r in rows
    ]

    js = (
        "// Auto-generated by export.py — do not edit by hand.\n"
        f"window.EXPENSE_DATA = {json.dumps(public_rows, ensure_ascii=False, indent=2)};\n"
        f"window.EXPENSE_CONFIG = {json.dumps(public_config, ensure_ascii=False, indent=2)};\n"
    )

    DATA_JS_PATH.write_text(js, encoding="utf-8")
    return len(public_rows)


if __name__ == "__main__":
    db.init_db()
    n = export()
    print(f"Exported {n} transactions to {DATA_JS_PATH}")
